variant: fcos
version: 1.5.0
storage:
  filesystems:
    - path: /home
      device: "/dev/vda3"
      format: btrfs
      wipe_filesystem: false
      mount_options:
        - "subvol=/@/home"
  files:
    - path: /etc/hostname
      overwrite: true
      contents:
        inline: |
          uos-ign
    - path: /etc/hosts
      append:
        - inline: |
            127.0.0.2 uos-ign.example.com uos-ign
passwd:
  users:
    - name: root
      password_hash: '$6$tZHO6G1SC8xvduBN$IG2QkzpmDxQw9bYz7MTTrigS83TtHacYY6t8Ea7qcpHt/81pwEc1.pTsCNC3O0RT4fB82kCxQs6OP7XwVKB071'
      ssh_authorized_keys_local:
        - microos_id_ed25519.pub
    - name: core
      ssh_authorized_keys_local:
        - microos_id_ed25519.pub
